site_name: Django IncludeContents
site_description: Component-like Django template tags with HTML syntax
site_url: https://smileychris.github.io/django-includecontents/
repo_url: https://github.com/SmileyChris/django-includecontents
repo_name: django-includecontents

theme:
  name: material
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mike:
      version_selector: true
      css_dir: css
      javascript_dir: js
      canonical_version: latest
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Basic Concepts: getting-started/basic-concepts.md
    - Tooling & Integration:
      - Prettier Formatting: tooling-integration/prettier-formatting.md
      - Tailwind CSS: tooling-integration/tailwind-css.md
      - Custom Engine: tooling-integration/custom-engine.md
      - Multi-line Tags: tooling-integration/multiline-tags.md
      - VS Code Setup: tooling-integration/vscode-setup.md
  - Using Components:
    - HTML Syntax: using-components/html-syntax.md
    - Template Tag Syntax: using-components/template-tag-syntax.md
    - Props & Attributes: using-components/props-and-attrs.md
    - Named Content Blocks: using-components/named-content-blocks.md
    - Wrapif Tag: using-components/wrapif-tag.md
  - Icons: 
    - Overview: icons.md
    - Styling with CSS Variables: icons/styling-with-css-variables.md
  - Showcase:
    - Overview: showcase/index.md
    - Component Discovery: showcase/component-discovery.md
    - Metadata Reference: showcase/metadata.md
    - Live Preview: showcase/live-preview.md
    - Showcase Templates: showcase/showcase-templates.md
    - Customisation Tips: showcase/customisation.md
  - Developing:
    - Example Project: example-project.md
    - Building Components:
      - Component Patterns: building-components/component-patterns.md
      - Advanced Props: building-components/advanced-props.md
      - CSS & Styling: building-components/css-and-styling.md
      - Best Practices: building-components/best-practices.md
    - Reference:
      - API Reference: reference/api-reference.md
      - Migration Guide: reference/migration-guide.md
      - Troubleshooting: reference/troubleshooting.md
      - Development: reference/development.md

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SmileyChris/django-includecontents
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/django-includecontents/
