[project]
name = "djangox"
version = "0.1.0"
description = "Django templates component engine"
authors = [{ name = "Chris Beaven", email = "smileychris@gmail.com" }]
dependencies = ["django"]
requires-python = ">=3.8"
readme = "README.md"
license = { text = "MIT" }

[project.optional-dependencies]
test = ["pytest", "pytest-django"]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "tests.settings"
django_find_project = false
pythonpath = "."
