name: Release new version

on:
  workflow_call:
  workflow_dispatch:

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/setup-python@v5
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Install package
        run: |
          python -m pip install -e .[deploy]
      - name: Test that the version is working correctly
        run: |
          python -c "import includecontents; print(includecontents.__version__)"
    #   - name: Ensure we're on a release version
    #     run:
    #       python -m includecontents.next_version
    #   - name: Upload
    #     run: pdm publish
