name: Publish to PyPI

on:
  release:
    types:
      - released

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/setup-python@v5
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Install package
        run: |
          python -m pip install -e .[deploy]
      - name: Ensure we're on a release version
        run: python -m includecontents.next_version
      - name: Upload
        run: pdm publish
